
import { Translation, Translations, User, ActivityCategory, Member, CommitteeRole } from './types';

export const INITIAL_USERS: User[] = [
  { 
    id: '1', 
    firstName: 'Angelus', 
    lastName: 'Supreme', 
    gender: 'M',
    pin: '1999', 
    role: 'admin',
    email: 'angelus@foiparfaite.org',
    phone: '+1 800 777 0000',
    address: 'Celestial Plaza, HQ',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    updatedAt: new Date(2024, 0, 1).toISOString(),
    deletedAt: null
  }
];

export const INITIAL_MEMBERS: Member[] = [];

export const DEFAULT_GOOGLE_CREDENTIALS = {
  "type": "service_account",
  "project_id": "gen-lang-client-0157459059",
  "private_key_id": "a9f797ed07b7e13b1d310f8eeae5e5cd0eaf1f9e",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHWLAD6jNOvSmd\nnkx7AGAhBq5nbeSr1Ir4g9I/EoDrzn61rCTzjGfLNsDR0cJfzNTFue4YADhmF4br\nWTN2zNoRn1zLRmW/Ns7A7NoTmNALbVx0Ik/ptjsOFVFFUDKxNEtRvdIYR9fKVrOS\nkp3iXjjrK6otPIkh6QOsXEnVLryEDlGpgkaLyTKef1wcr8E83jAWXDdic0SPU3sx\nDEylqobsDo+EZCok8cna091/PUZ6VMdTHPLAMHFSOziDPNlRsDpTWib1sqGkWIFO\nQpct99oD0+bSSzbnEw/6wBG4hFQFA52tPVu59i4Vy8UcQG9OccMO4b3rB/SBxoG+\nUGchwRGTAgMBAAECggEAHlEGYm9dgoXcdzGUrQd3bHO2gK6i87Tntk1fOKNeQukN\nC8upykuZ72WczmwUSlB9iAfeRf0mlp7RBdLI3lzfdIWkGEVVAk8ErizMf5AiYlKC\nmHuCuWbdiqdC9wPFfyiWTyX19nuv6CrmYA33KpmCFisg/tncJcbo/ZoCyoPd50Z8\nTPSJN6G30ISR2PE4qVJczZODKRQH+MWMqeMr00I/uYlMs+AkOWY+ixLNTl6J/7gY\noRc4vFEQ1Q3EjLlEw1whyNVQiX8jZFTyoN0cy22KaYIqkukA8jv3qqqZf5womQMZ\nhImzTqkSXbM/Z2pdXA0eD14CT+R8KVMEniyN2dZrvQKBgQD/pFXCMs1+1PItoml8\nYTUAvRkQ5inM1tE+32vGxr8uYttBl8s2sHhTXtDQIOal04IP4YJNa+pSQHnOzVr+\nWKk+B/yl0JGw+6i00jqdgx1NZjRQBQPc7ps4VVqcBT2cvEXEk1Dz48QQqVuJGnTp\nof9IWZ5btfSBDpliZAbmVzE9vwKBgQDHoCqzpZdIfFPhoJLYwazn9mnPHFf2HTLL\AYgyqCb91qdJzTBAVphHKOyfoxE/JfiOBG7aTc1UItv6MbTm/6pSjxpljRfxzpXF\nqmdjLCyfMYMt29lKMZpPZluoGQqMHr3B5CMpbw9boEoj/c+pyx7Dn9pTm5qHKw5j\nKTLES3KJLQKBgQCFN7YZBTBhL8ckUMZ3spBUWjZ9v/N4c1mHUhZv95IZMhrgC6Iy\nVbPefkKCsyJ+t8HHVNT6U4pAYqkXQ5xvfvRzBuZ54j6J5Br+X6979Z+HfgM0z+g7\ncXwh1xjoxTJeQx54WeyNq9u4cwjoYYkbVvgZU9paIG/R8TGtPEL8NePLMQKBgENQ\Q/Xt6ZR8sABOGBZVQIu7cLRw90w7TkxcCOQkBXnk7uYY9aNMT+724st1vjQQBr9E\nyWh9gbZURt8X8ctO/Mz4CkuiByf3pFNSAajUVXucw4IsNxooncMWXePSBdd36j6+\nQgkPtRsNctKuHF9B6e7HMWSt/K6Fm0VeuAqu8kFFAoGAS36Tvbn78WCml/YL09/r\nIKh+MPrsuBL/sagjhocoFmtGAk0w5Gz2QOEhthejTJUGXrA6h5MMj/VuYGv1Hf32\nuWw1ij67BqrE950g2WOCAi3KUZRpqTUzNyxLYBEaGrz+IaDaOXEUjeCotZwaY5e4\n6tAJ1iRueyybQWfHJI0gBNA=\n-----END PRIVATE KEY-----\n",
  "client_email": "google-sheets-service@gen-lang-client-0157459059.iam.gserviceaccount.com",
  "client_id": "116830194381938429970",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/google-sheets-service%40gen-lang-client-0157459059.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
};

export const INITIAL_COMMITTEE_ROLES: CommitteeRole[] = [
  { id: '1', name: 'President', description: 'Leads the committee' },
  { id: '2', name: 'Vice President', description: 'Substitutes the president' },
  { id: '3', name: 'Secretary', description: 'Administration' },
  { id: '4', name: 'Treasurer', description: 'Fund management' },
  { id: '5', name: 'Member', description: 'Operational support' }
];

export const INITIAL_COMMITTEE_TYPES: string[] = [
  'Executive Committee',
  'Financial Committee',
  'Events Committee',
  'Disciplinary Committee',
  'Spiritual Committee'
];

export const MEMBER_TYPES: string[] = ['Regular', 'Ministry Leader', 'Pastor', 'Missionary', 'Visitor', 'Baptized'];

export const DEPARTMENT_LIST = ['Worship', 'Ushers', 'Children', 'Men', 'Women', 'Youth', 'Education', 'Missions', 'Technology'];

export const TRANSLATIONS: Translations = {
  en: {
    welcome: 'Welcome',
    enterPin: 'Enter PIN',
    wrongPin: 'Incorrect PIN',
    loading: 'Loading...',
    guest: 'Guest',
    menuTitle: 'Main Menu',
    logout: 'Logout',
    settings: 'Settings',
    profile: 'Profile',
    apps: 'Applications',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    gender: 'Gender',
    role: 'Role',
    changePin: 'Change PIN',
    save: 'Save',
    edit: 'Edit',
    cancel: 'Cancel',
    pinRestriction: 'Super users cannot change their PIN',
    userManagement: 'User Management',
    createUser: 'Create User',
    addUser: 'Add User',
    userList: 'User List',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    activities: 'Activities',
    createActivity: 'Create Activity',
    activityTitle: 'Title',
    category: 'Category',
    subType: 'Type',
    department: 'Department',
    status: 'Status',
    time: 'Time',
    participants: 'Participants',
    addParticipant: 'Add Participant',
    delete: 'Delete',
    active: 'Active',
    inactive: 'Inactive',
    ongoing: 'Ongoing',
    cancelled: 'Cancelled',
    members: 'Members',
    memberList: 'Member List',
    addMember: 'Add Member',
    editMember: 'Edit Member',
    age: 'age',
    memberType: 'Member Type',
    personalInfo: 'Personal Info',
    contactInfo: 'Contact Info',
    spiritualInfo: 'Spiritual Info',
    churchStatus: 'Church Status',
    familyInfo: 'Family Info',
    tithes: 'Tithes',
    addTithe: 'Add Tithe',
    amount: 'Amount',
    offerings: 'Offerings',
    addOffering: 'Add Offering',
    donations: 'Donations',
    addDonation: 'Add Donation',
    expenses: 'Expenses',
    addExpense: 'Add Expense',
    prayers: 'Prayers',
    addPrayer: 'Add Prayer',
    birthdays: 'Birthdays',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    analytics: 'Financial Analysis',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Balance',
    aiInsights: 'Smart Insights',
    roleManagement: 'Role Management',
    globalLanguage: 'Global Language',
    all: 'All',
    details: 'Details',
    notesLabel: 'Notes',
    confirmAction: 'Please confirm',
    mandatoryField: 'This field is mandatory',
    roles: { admin: 'Administrator', secretaria: 'Secretary', contable: 'Accountant', user: 'User', super: 'Super User' },
    moduleNames: { 
      members: 'Members', activities: 'Activities', tithes: 'Tithes', offerings: 'Offerings', 
      donations: 'Donations', expenses: 'Expenses', prayers: 'Prayers', analytics: 'Analysis', 
      birthdays: 'Birthdays', calendar: 'Calendar', committee: 'Committees', 
      attendanceCommunion: 'Attendance', digitalID: 'Digital ID', idTypes: 'ID Types', 
      notifications: 'Notifications', sundaySchool: 'Sunday School'
    },
    forgotPin: 'Forgot PIN?',
    clear: 'Clear',
    fiscalYear: 'Fiscal Year',
    income: 'Income',
    expensesTitle: 'Expenses',
    balance: 'Balance',
    searchBy: 'Search by...',
    sessionID: 'Session ID',
    startingSession: 'Starting Session',
    identityVerification: 'Identity Verification',
    syncing: 'Syncing...',
    accessGranted: 'Access Granted',
    manualEntry: 'Manual Entry',
    registrationOpen: 'Registration Open',
    registrationClosed: 'Registration Closed',
    attendance: 'Attendance',
    holyCommunion: 'Holy Communion',
    selectActiveEvent: 'Select Active Event',
    close: 'Close',
    register: 'Register',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    registrationSuccess: 'Registration Successful!',
    yourPinIs: 'Your login PIN is:',
    staffTitle: 'Staff Management',
    staffSubtitle: 'Administrative Management',
    staffOnlyRead: 'Read Only',
    staffVerifying: 'Verifying...',
    staffUniquePin: 'PIN (Unique 4 digits)',
    staffAccessPanel: 'This PIN will allow access to this panel',
    incompleteTitle: 'Incomplete Profiles',
    incompleteSub: 'Members requiring attention',
    incompleteFields: 'Fields missing',
    incompleteCompleteBtn: 'Complete Profile',
    incompleteAllDone: 'Excellent! All profiles are complete',
    auditAlert: 'AUDIT ALERT',
    auditMessage: '{user} ({role}) {action} a record in [{table}]: "{item}".',
    auditActionEdit: 'edited',
    auditActionDelete: 'deleted',
    conversionDate: 'Conversion Date',
    baptismDate: 'Baptism Date',
    baptismPlace: 'Baptism Place',
    questions: {
      firstName: 'What is your first name?', lastName: 'What is your last name?',
      gender: 'Select your gender', birthDate: 'When is your birthday?',
      email: 'What is your email address?', phone: 'What is your phone number?',
      address: 'Where do you live?', nationality: 'What is your nationality?',
      language: 'What is your primary language?', baptized: 'Are you baptized?',
      civilStatus: 'What is your civil status?', photo: 'Finally, let\'s take a photo of you',
      conversionDate: 'When did you convert?', baptismDate: 'When were you baptized?',
      baptismPlace: 'Where were you baptized?'
    },
    listMemberTypes: ['Regular', 'Leader', 'Pastor', 'Missionary', 'Visitor'],
    listGenders: ['Male', 'Female', 'Other'],
    listCivilStatuses: ['Single', 'Married', 'Divorced', 'Widowed'],
    listNationalities: ['American', 'Haitian', 'Dominican', 'French', 'Other'],
    listLanguages: ['English', 'Spanish', 'French', 'Creole'],
    listSpiritualStatuses: ['Baptized', 'Not Baptized', 'Candidate'],
    listDepartments: ['Worship', 'Ushers', 'Kids', 'Youth', 'Ladies', 'Men'],
    listSpouseRelationshipTypes: ['Spouse', 'Partner', 'Fiancé'],
    listExpenseCategories: ['Rent', 'Utilities', 'Maintenance', 'Other'],
    listCommitteeTypes: ['Executive', 'Finance', 'Events', 'Spiritual'],
    listIDTypes: ['ID Card', 'Passport', 'Driver License'],
    pinDisplayPrompt: 'Secure Access',
    pinDisplaySub: 'Enter your 4-digit PIN to access. The system will validate automatically.',
    forgotPinHelp: 'Please complete your details so the admin team can verify your identity.',
    forgotPinSent: 'Request Sent',
    forgotPinSentSub: 'An administrator will contact you soon.',
    forgotPinBtn: 'Request Help',
    committeeMembers: 'Committee Members',
    committeeLogo: 'Committee Logo',
    committeeType: 'Committee Type',
    committeeStartDate: 'Start Date',
    committeeFunction: 'Position Function',
    sundaySchool: 'Sunday School',
    send: 'Send',
    notifications: {
      newNotification: 'New Notification',
      sendTo: 'Send To',
      global: 'Global',
      roles: 'Roles',
      members: 'Members',
      clearRead: 'Clear Read',
      clearAll: 'Clear All',
      from: 'From',
      noNotifications: 'No Notifications',
      status: 'Status',
      read: 'Read',
      unread: 'Unread'
    }
  }
};
